"""Structured Session schema for Phase 1 of REFATOR_PLAN.md.

This module defines the structured domain blocks that replace the legacy flat
session dict in later phases:

    Session
    ├── identity
    ├── focus
    ├── baseline_workspace
    ├── history
    ├── execution_state
    ├── ui_state
    ├── operational_state
    └── lifecycle

The dataclasses here are the *single source of truth* for the v1 schema shape.
``SessionV1Store`` (in ``store.py``) handles persistence and legacy migration.

Invariants enforced at this layer:

* ``identity.schema_version`` is always ``"1.0"`` after construction.
* There are no approval tokens, plan tokens, or ``presented_plan_*`` fields
  anywhere in this schema (removed through the Onda 1 series).
* Updating ``focus`` marks the baseline stale.

These invariants live on the dataclasses themselves so that any future
consumer (the runtime, the router, tests) cannot skip them by accident.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import uuid4


SCHEMA_VERSION = "1.0"
CANONICAL_LANGUAGE = "en"

# Bounds. Phase 1 mirrors the legacy chat-history bound so behaviour matches
# during the coexistence window.
DEFAULT_MAX_HISTORY_MESSAGES = 80
DEFAULT_MAX_PRIOR_SESSION_IDS = 16
DEFAULT_MAX_LIFECYCLE_NOTES = 32

# Allowed phases for ``execution_state.phase``. Kept as a frozenset rather than
# a literal type so the validation cost is one membership test.
EXECUTION_PHASES: frozenset[str] = frozenset(
    {
        "idle",
        "reading",
        "executing",
        "drafting",
        "failed",
        "halted",
    }
)
VALID_DRAFT_EDIT_MODES: frozenset[str] = frozenset(
    {
        "preserve_and_refine",
        "intentional_rebuild",
        "intentional_retarget",
    }
)

# Onda 3: persisted session work state. Mirrors routing_obs.SESSION_STATES.
# IDLE → no draft, no recent failure
# EXPLORING → reading scene/GN
# DRAFTING → drafting an unexecuted script
# PENDING_USER_EXECUTION → draft newer than what was last executed
# REPAIRING → last execution failed, draft needs a fix
# RESOLVED → last execution succeeded for current revision
# STRATEGY_PROPOSED / STRATEGY_APPROVED → post-failure diagnosis subflow:
# the agent proposed options after a failed draft, then the user approved one.
SESSION_STATES: frozenset[str] = frozenset(
    {
        "IDLE",
        "EXPLORING",
        "DRAFTING",
        "PENDING_USER_EXECUTION",
        "REPAIRING",
        "STRATEGY_PROPOSED",
        "STRATEGY_APPROVED",
        "RESOLVED",
    }
)


# ---------------------------------------------------------------------------
# Onda 5: work-cycle types
# ---------------------------------------------------------------------------


class WorkCyclePhase(str, Enum):
    """UX cycle phase shown in the panel (Item 5.2 / Onda 5).

    Distinct from ExecutionState.phase (internal runtime phase).
    Drives the 4-state panel layout: CONVERSA / PRONTO / EXECUTANDO / RESULTADO.
    """
    IDLE = "idle"
    PENDING_USER_EXECUTION = "pending_user_execution"
    EXECUTING = "executing"
    AWAITING_FEEDBACK = "awaiting_feedback"


WORK_CYCLE_PHASES: frozenset[str] = frozenset(p.value for p in WorkCyclePhase)


@dataclass
class DraftRevision:
    """One saved revision of a script draft (appended on each write_script_draft success)."""
    revision: int = 0
    timestamp: str = ""
    char_count: int = 0
    snapshot_ref: str = ""   # filename of associated blend snapshot, or ""
    label: str = ""          # short description generated by the agent, or ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "revision": int(self.revision),
            "timestamp": self.timestamp,
            "char_count": int(self.char_count),
            "snapshot_ref": self.snapshot_ref,
            "label": self.label,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any] | None) -> "DraftRevision":
        data = data or {}
        return cls(
            revision=int(data.get("revision") or 0),
            timestamp=str(data.get("timestamp") or ""),
            char_count=int(data.get("char_count") or 0),
            snapshot_ref=str(data.get("snapshot_ref") or ""),
            label=str(data.get("label") or ""),
        )


@dataclass
class TaskInfo:
    """An in-progress designer task scoped to the current session."""
    task_id: str = ""
    label: str = ""
    started_at: str = ""
    ended_at: str = ""    # ISO 8601 or "" if still in progress

    def __post_init__(self) -> None:
        if not self.task_id:
            self.task_id = str(uuid4())
        if not self.started_at:
            self.started_at = utc_now_iso()

    def to_dict(self) -> dict[str, Any]:
        return {
            "task_id": self.task_id,
            "label": self.label,
            "started_at": self.started_at,
            "ended_at": self.ended_at,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any] | None) -> "TaskInfo | None":
        if not isinstance(data, dict) or not data:
            return None
        return cls(
            task_id=str(data.get("task_id") or ""),
            label=str(data.get("label") or ""),
            started_at=str(data.get("started_at") or ""),
            ended_at=str(data.get("ended_at") or ""),
        )


@dataclass
class PendingUserDecision:
    """Operational decision prompt waiting for the next user turn."""

    kind: str = ""
    options: list[str] = field(default_factory=list)
    prompt_summary: str = ""
    source_revision: int = 0
    related_failure: str = ""
    proposed_at_turn: int = 0
    proposed_at_run_id: str = ""
    status: str = "pending"
    answered_with: str = ""
    answered_at_turn: int = 0

    def __post_init__(self) -> None:
        self.kind = str(self.kind or "")
        self.options = [str(item) for item in (self.options or []) if str(item).strip()]
        self.prompt_summary = str(self.prompt_summary or "")[:140]
        self.source_revision = int(self.source_revision or 0)
        self.related_failure = str(self.related_failure or "")
        self.proposed_at_turn = int(self.proposed_at_turn or 0)
        self.proposed_at_run_id = str(self.proposed_at_run_id or "")
        if self.status not in {"pending", "answered", "cancelled", "expired"}:
            self.status = "pending"
        self.answered_with = str(self.answered_with or "")
        self.answered_at_turn = int(self.answered_at_turn or 0)

    def to_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "options": list(self.options),
            "prompt_summary": self.prompt_summary,
            "source_revision": int(self.source_revision),
            "related_failure": self.related_failure,
            "proposed_at_turn": int(self.proposed_at_turn),
            "proposed_at_run_id": self.proposed_at_run_id,
            "status": self.status,
            "answered_with": self.answered_with,
            "answered_at_turn": int(self.answered_at_turn),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any] | None) -> "PendingUserDecision | None":
        if not isinstance(data, dict) or not data:
            return None
        options = data.get("options") if isinstance(data.get("options"), list) else []
        return cls(
            kind=str(data.get("kind") or ""),
            options=[str(item) for item in options if str(item).strip()],
            prompt_summary=str(data.get("prompt_summary") or "")[:140],
            source_revision=int(data.get("source_revision") or 0),
            related_failure=str(data.get("related_failure") or ""),
            proposed_at_turn=int(data.get("proposed_at_turn") or 0),
            proposed_at_run_id=str(data.get("proposed_at_run_id") or ""),
            status=str(data.get("status") or "pending"),
            answered_with=str(data.get("answered_with") or ""),
            answered_at_turn=int(data.get("answered_at_turn") or 0),
        )


def utc_now_iso() -> str:
    """Return a stable, second-precision UTC ISO-8601 timestamp."""
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def new_session_id() -> str:
    """Generate a new opaque session id."""
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    return f"sess-{ts}-{uuid4().hex[:8]}"


def new_continuity_token() -> str:
    """Generate an opaque continuity token used to reattach across restarts."""
    return f"cont-{uuid4().hex[:12]}"


def compute_focus_signature(
    blend_path: str | None,
    object_name: str | None,
    modifier_name: str | None,
    tree_name: str | None,
) -> str:
    """Compute a stable signature for the current focus.

    The signature is a short hex digest of the four focus coordinates joined
    by ``|``. ``None`` and empty strings are normalised so that two equivalent
    focuses always produce the same signature.
    """
    parts = [
        str(blend_path or ""),
        str(object_name or ""),
        str(modifier_name or ""),
        str(tree_name or ""),
    ]
    raw = "|".join(parts).encode("utf-8")
    return hashlib.sha1(raw).hexdigest()[:16]


# ---------------------------------------------------------------------------
# Domain blocks
# ---------------------------------------------------------------------------


@dataclass
class Identity:
    session_id: str = field(default_factory=new_session_id)
    schema_version: str = SCHEMA_VERSION
    created_at: str = field(default_factory=utc_now_iso)
    last_active_at: str = field(default_factory=utc_now_iso)
    canonical_language: str = CANONICAL_LANGUAGE

    def touch(self) -> None:
        self.last_active_at = utc_now_iso()

    def to_dict(self) -> dict[str, Any]:
        return {
            "session_id": self.session_id,
            "schema_version": self.schema_version,
            "created_at": self.created_at,
            "last_active_at": self.last_active_at,
            "canonical_language": self.canonical_language,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any] | None) -> "Identity":
        data = data or {}
        return cls(
            session_id=str(data.get("session_id") or new_session_id()),
            schema_version=str(data.get("schema_version") or SCHEMA_VERSION),
            created_at=str(data.get("created_at") or utc_now_iso()),
            last_active_at=str(data.get("last_active_at") or utc_now_iso()),
            canonical_language=str(data.get("canonical_language") or CANONICAL_LANGUAGE),
        )


@dataclass
class Focus:
    blend_path: str = ""
    object_name: str | None = None
    modifier_name: str | None = None
    tree_name: str | None = None
    focus_signature: str = ""
    focus_changed_at: str = field(default_factory=utc_now_iso)

    def __post_init__(self) -> None:
        if not self.focus_signature:
            self.focus_signature = compute_focus_signature(
                self.blend_path, self.object_name, self.modifier_name, self.tree_name
            )

    def to_dict(self) -> dict[str, Any]:
        return {
            "blend_path": self.blend_path,
            "object_name": self.object_name,
            "modifier_name": self.modifier_name,
            "tree_name": self.tree_name,
            "focus_signature": self.focus_signature,
            "focus_changed_at": self.focus_changed_at,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any] | None) -> "Focus":
        data = data or {}
        focus = cls(
            blend_path=str(data.get("blend_path") or ""),
            object_name=_optional_str(data.get("object_name")),
            modifier_name=_optional_str(data.get("modifier_name")),
            tree_name=_optional_str(data.get("tree_name")),
            focus_signature=str(data.get("focus_signature") or ""),
            focus_changed_at=str(data.get("focus_changed_at") or utc_now_iso()),
        )
        # Recompute the signature if it was missing or stale relative to coords.
        expected = compute_focus_signature(
            focus.blend_path, focus.object_name, focus.modifier_name, focus.tree_name
        )
        if focus.focus_signature != expected:
            focus.focus_signature = expected
        return focus


@dataclass
class BaselineWorkspace:
    tree_signature: str = ""
    built_at: str = ""
    built_from: str = ""  # "auto" | "user_request" | "post_mutation" | ""
    structural_summary: dict[str, Any] = field(default_factory=dict)
    semantic_layers: list[dict[str, Any]] = field(default_factory=list)
    subgraph_index: dict[str, Any] = field(default_factory=dict)
    recipe_associations: list[dict[str, Any]] = field(default_factory=list)
    known_parameters: dict[str, Any] = field(default_factory=dict)
    open_questions: list[str] = field(default_factory=list)
    stale: bool = True  # an empty baseline is always stale until built

    def is_built(self) -> bool:
        return bool(self.tree_signature) and bool(self.built_at)

    def mark_stale(self) -> None:
        self.stale = True

    def to_dict(self) -> dict[str, Any]:
        # Use isinstance guards so that a wrong-typed value (e.g. a string
        # accidentally stored in structural_summary) never raises a TypeError
        # or ValueError during serialisation.
        return {
            "tree_signature": self.tree_signature,
            "built_at": self.built_at,
            "built_from": self.built_from,
            "structural_summary": dict(self.structural_summary) if isinstance(self.structural_summary, dict) else {},
            "semantic_layers": [dict(item) for item in self.semantic_layers if isinstance(item, dict)],
            "subgraph_index": dict(self.subgraph_index) if isinstance(self.subgraph_index, dict) else {},
            "recipe_associations": [dict(item) for item in self.recipe_associations if isinstance(item, dict)],
            "known_parameters": dict(self.known_parameters) if isinstance(self.known_parameters, dict) else {},
            "open_questions": list(self.open_questions),
            "stale": bool(self.stale),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any] | None) -> "BaselineWorkspace":
        data = data or {}
        return cls(
            tree_signature=str(data.get("tree_signature") or ""),
            built_at=str(data.get("built_at") or ""),
            built_from=str(data.get("built_from") or ""),
            structural_summary=_as_dict(data.get("structural_summary")),
            semantic_layers=_as_list_of_dicts(data.get("semantic_layers")),
            subgraph_index=_as_dict(data.get("subgraph_index")),
            recipe_associations=_as_list_of_dicts(data.get("recipe_associations")),
            known_parameters=_as_dict(data.get("known_parameters")),
            open_questions=[str(item) for item in (data.get("open_questions") or []) if str(item).strip()],
            stale=bool(data.get("stale", True)),
        )


@dataclass
class HistoryMessage:
    role: str  # "user" | "assistant" | "system"
    content: str
    ts: str = field(default_factory=utc_now_iso)
    turn_class: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "role": self.role,
            "content": self.content,
            "ts": self.ts,
            "turn_class": self.turn_class,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "HistoryMessage":
        return cls(
            role=str(data.get("role") or "").strip().lower() or "system",
            content=str(data.get("content") or ""),
            ts=str(data.get("ts") or utc_now_iso()),
            turn_class=str(data.get("turn_class") or ""),
        )


@dataclass
class History:
    max_messages: int = DEFAULT_MAX_HISTORY_MESSAGES
    messages: list[HistoryMessage] = field(default_factory=list)
    older_summary: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "max_messages": self.max_messages,
            "messages": [msg.to_dict() for msg in self.messages],
            "older_summary": self.older_summary,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any] | None) -> "History":
        data = data or {}
        raw_messages = data.get("messages") or []
        messages: list[HistoryMessage] = []
        for item in raw_messages:
            if isinstance(item, dict):
                messages.append(HistoryMessage.from_dict(item))
        older_summary = data.get("older_summary")
        return cls(
            max_messages=int(data.get("max_messages") or DEFAULT_MAX_HISTORY_MESSAGES),
            messages=messages,
            older_summary=str(older_summary) if older_summary else None,
        )


@dataclass
class DraftedScript:
    """Metadata for a script drafted into a Blender Text Editor block.

    The actual script content lives in ``bpy.data.texts[block_name]``.
    This dataclass tracks the draft lifecycle on the session side.
    """

    block_name: str = "GN_Agent_Draft"
    description: str = ""
    tree_name: str = ""
    version: int = 1
    drafted_at: str = field(default_factory=utc_now_iso)
    revision_parent: int = 0
    revision_kind: str = "create"
    revision_changed_from_previous: str = ""
    revision_validity: str = "partial"
    
    # Draft metadata state
    status: str = "partial" # "open", "partial", "incomplete", "ready"
    last_written_chars: int = 0
    appended_last: bool = False
    target_region: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "block_name": self.block_name,
            "description": self.description,
            "tree_name": self.tree_name,
            "version": int(self.version),
            "drafted_at": self.drafted_at,
            "revision_parent": int(self.revision_parent),
            "revision_kind": self.revision_kind,
            "revision_changed_from_previous": self.revision_changed_from_previous,
            "revision_validity": self.revision_validity,
            "status": self.status,
            "last_written_chars": int(self.last_written_chars),
            "appended_last": bool(self.appended_last),
            "target_region": self.target_region,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any] | None) -> "DraftedScript | None":
        if not isinstance(data, dict) or not data:
            return None
        return cls(
            block_name=str(data.get("block_name") or "GN_Agent_Draft"),
            description=str(data.get("description") or ""),
            tree_name=str(data.get("tree_name") or ""),
            version=int(data.get("version") or 1),
            drafted_at=str(data.get("drafted_at") or utc_now_iso()),
            revision_parent=int(data.get("revision_parent") or 0),
            revision_kind=str(data.get("revision_kind") or "create"),
            revision_changed_from_previous=str(data.get("revision_changed_from_previous") or ""),
            revision_validity=str(data.get("revision_validity") or "partial"),
            status=str(data.get("status") or "partial"),
            last_written_chars=int(data.get("last_written_chars") or 0),
            appended_last=bool(data.get("appended_last") or False),
            target_region=str(data.get("target_region") or ""),
        )




@dataclass
class LastFailure:
    tool: str = ""
    error: str = ""
    cause: str = ""
    suggested_alternative: str = ""
    failed_at: str = field(default_factory=utc_now_iso)

    def to_dict(self) -> dict[str, Any]:
        return {
            "tool": self.tool,
            "error": self.error,
            "cause": self.cause,
            "suggested_alternative": self.suggested_alternative,
            "failed_at": self.failed_at,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any] | None) -> "LastFailure | None":
        if not isinstance(data, dict) or not data:
            return None
        return cls(
            tool=str(data.get("tool") or ""),
            error=str(data.get("error") or ""),
            cause=str(data.get("cause") or ""),
            suggested_alternative=str(data.get("suggested_alternative") or ""),
            failed_at=str(data.get("failed_at") or utc_now_iso()),
        )


@dataclass
class ExecutionState:
    """Execution phase and failure record.

    Phase 7: ``consecutive_failures`` removed.  The one-shot failure policy
    (§2.5 of REFATOR_PLAN.md) means there is never a retry counter to track:
    one failure → explain-and-stop → user decides.

    ``drafting_mode``: when True, mutation requests produce scripts in
    Blender's Text Editor instead of staging for auto-replay.  The user
    controls execution manually.
    """

    phase: str = "idle"
    last_failure: LastFailure | None = None
    drafting_mode: bool = False
    current_draft: DraftedScript | None = None
    draft_revision: int = 0
    draft_block_name: str = "GN_Agent_Draft"
    draft_target_tree: str = ""
    last_executed_revision: int = 0
    last_execution_outcome: str = ""
    last_execution_notes: str = ""
    scene_reverted_by_user: bool = False
    retry_requires_draft_change: bool = False
    last_saved_char_count: int = 0
    last_saved_summary: str = ""
    revision_created_at: str = ""
    revision_parent: int = 0
    revision_kind: str = ""
    revision_changed_from_previous: str = ""
    current_revision_validity: str = ""
    last_valid_draft_revision: int = 0
    last_failed_revision: int = 0
    pending_draft_action: str = ""
    pending_draft_prompt: str = ""
    draft_edit_mode: str = "preserve_and_refine"
    post_failure_state: str = ""
    proposed_strategy_count: int = 0
    proposed_strategy_revision: int = 0
    approved_strategy_label: str = ""
    approved_strategy_prompt: str = ""
    pending_user_decision: PendingUserDecision | None = None
    # Onda 3: high-level session work state, persisted via SessionStateStore.
    # The field mirrors what the dedicated store contains so handlers can read
    # it without an extra disk hit. SESSION_STATES enumerates valid values.
    session_state: str = "IDLE"
    # Onda 5 (Item 5.2): UX cycle phase for the 4-state panel layout.
    # Distinct from `phase` (internal runtime phase).
    work_cycle_phase: str = WorkCyclePhase.IDLE.value
    # History of saved draft revisions for the current task.
    draft_revisions: list[DraftRevision] = field(default_factory=list)
    # Index of the revision currently shown in the panel (1-based, 0 = none).
    current_revision: int = 0
    # Active designer task, or None if no task is started.
    current_task: TaskInfo | None = None

    def __post_init__(self) -> None:
        if self.phase not in EXECUTION_PHASES:
            self.phase = "idle"
        if self.draft_edit_mode not in VALID_DRAFT_EDIT_MODES:
            self.draft_edit_mode = "preserve_and_refine"
        if self.post_failure_state and self.post_failure_state not in {"DIAGNOSING", "STRATEGY_PROPOSED", "STRATEGY_APPROVED"}:
            self.post_failure_state = ""
        if self.session_state not in SESSION_STATES:
            self.session_state = "IDLE"
        if self.work_cycle_phase not in WORK_CYCLE_PHASES:
            self.work_cycle_phase = WorkCyclePhase.IDLE.value

    def set_phase(self, phase: str) -> None:
        if phase not in EXECUTION_PHASES:
            raise ValueError(f"unknown execution phase: {phase!r}")
        self.phase = phase

    def set_work_cycle_phase(self, phase: WorkCyclePhase | str) -> None:
        value = phase.value if isinstance(phase, WorkCyclePhase) else str(phase)
        if value not in WORK_CYCLE_PHASES:
            raise ValueError(f"unknown work cycle phase: {phase!r}")
        self.work_cycle_phase = value

    def to_dict(self) -> dict[str, Any]:
        return {
            "phase": self.phase,
            "last_failure": self.last_failure.to_dict() if self.last_failure else None,
            "drafting_mode": bool(self.drafting_mode),
            "current_draft": self.current_draft.to_dict() if self.current_draft else None,
            "draft_revision": int(self.draft_revision),
            "draft_block_name": self.draft_block_name,
            "draft_target_tree": self.draft_target_tree,
            "last_executed_revision": int(self.last_executed_revision),
            "last_execution_outcome": self.last_execution_outcome,
            "last_execution_notes": self.last_execution_notes,
            "scene_reverted_by_user": bool(self.scene_reverted_by_user),
            "retry_requires_draft_change": bool(self.retry_requires_draft_change),
            "last_saved_char_count": int(self.last_saved_char_count),
            "last_saved_summary": self.last_saved_summary,
            "revision_created_at": self.revision_created_at,
            "revision_parent": int(self.revision_parent),
            "revision_kind": self.revision_kind,
            "revision_changed_from_previous": self.revision_changed_from_previous,
            "current_revision_validity": self.current_revision_validity,
            "last_valid_draft_revision": int(self.last_valid_draft_revision),
            "last_failed_revision": int(self.last_failed_revision),
            "pending_draft_action": self.pending_draft_action,
            "pending_draft_prompt": self.pending_draft_prompt,
            "draft_edit_mode": self.draft_edit_mode,
            "post_failure_state": self.post_failure_state,
            "proposed_strategy_count": int(self.proposed_strategy_count),
            "proposed_strategy_revision": int(self.proposed_strategy_revision),
            "approved_strategy_label": self.approved_strategy_label,
            "approved_strategy_prompt": self.approved_strategy_prompt,
            "pending_user_decision": (
                self.pending_user_decision.to_dict()
                if isinstance(self.pending_user_decision, PendingUserDecision)
                else None
            ),
            "session_state": self.session_state,
            "work_cycle_phase": self.work_cycle_phase,
            "draft_revisions": [
                r.to_dict() if isinstance(r, DraftRevision) else dict(r)
                for r in (self.draft_revisions or [])
                if r is not None
            ],
            "current_revision": int(self.current_revision),
            "current_task": self.current_task.to_dict() if isinstance(self.current_task, TaskInfo) else None,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any] | None) -> "ExecutionState":
        data = data or {}
        # consecutive_failures was removed in Phase 7; silently ignore if present
        # in persisted sessions serialised by an older version.
        return cls(
            phase=str(data.get("phase") or "idle"),
            # pending_mutation removed in Onda 1F-C; silently discarded if present
            # in sessions serialised by an older version.
            last_failure=LastFailure.from_dict(data.get("last_failure")),
            drafting_mode=bool(data.get("drafting_mode", False)),
            current_draft=DraftedScript.from_dict(data.get("current_draft")),
            draft_revision=int(data.get("draft_revision") or 0),
            draft_block_name=str(data.get("draft_block_name") or "GN_Agent_Draft"),
            draft_target_tree=str(data.get("draft_target_tree") or ""),
            last_executed_revision=int(data.get("last_executed_revision") or 0),
            last_execution_outcome=str(data.get("last_execution_outcome") or ""),
            last_execution_notes=str(data.get("last_execution_notes") or ""),
            scene_reverted_by_user=bool(data.get("scene_reverted_by_user", False)),
            retry_requires_draft_change=bool(data.get("retry_requires_draft_change", False)),
            last_saved_char_count=int(data.get("last_saved_char_count") or 0),
            last_saved_summary=str(data.get("last_saved_summary") or ""),
            revision_created_at=str(data.get("revision_created_at") or ""),
            revision_parent=int(data.get("revision_parent") or 0),
            revision_kind=str(data.get("revision_kind") or ""),
            revision_changed_from_previous=str(data.get("revision_changed_from_previous") or ""),
            current_revision_validity=str(data.get("current_revision_validity") or ""),
            last_valid_draft_revision=int(data.get("last_valid_draft_revision") or 0),
            last_failed_revision=int(data.get("last_failed_revision") or 0),
            # reasoning_draft_revision removed in Onda 1A (2026-04-23); silently
            # ignored if present in sessions serialised by an older version.
            pending_draft_action=str(data.get("pending_draft_action") or ""),
            pending_draft_prompt=str(data.get("pending_draft_prompt") or ""),
            draft_edit_mode=str(data.get("draft_edit_mode") or "preserve_and_refine"),
            post_failure_state=str(data.get("post_failure_state") or ""),
            proposed_strategy_count=int(data.get("proposed_strategy_count") or 0),
            proposed_strategy_revision=int(data.get("proposed_strategy_revision") or 0),
            approved_strategy_label=str(data.get("approved_strategy_label") or ""),
            approved_strategy_prompt=str(data.get("approved_strategy_prompt") or ""),
            pending_user_decision=PendingUserDecision.from_dict(data.get("pending_user_decision")),
            session_state=str(data.get("session_state") or "IDLE"),
            # Onda 5 migration: old sessions missing these fields default safely.
            work_cycle_phase=str(data.get("work_cycle_phase") or WorkCyclePhase.IDLE.value),
            draft_revisions=[
                DraftRevision.from_dict(r)
                for r in (data.get("draft_revisions") or [])
                if isinstance(r, dict)
            ],
            current_revision=int(data.get("current_revision") or 0),
            current_task=TaskInfo.from_dict(data.get("current_task")),
        )


@dataclass
class UIState:
    advanced_open: bool = False
    debug_mode: bool = False
    explicit_override_mode: bool = False
    mcp_write_enabled: bool = False
    simulate_bridge_failure: bool = False
    last_screenshot_meta: dict[str, Any] | None = None
    session_active: bool = False  # Phase 9: V1 session gate (replaces legacy agent_session_active)

    def to_dict(self) -> dict[str, Any]:
        return {
            "advanced_open": bool(self.advanced_open),
            "debug_mode": bool(self.debug_mode),
            "explicit_override_mode": bool(self.explicit_override_mode),
            "mcp_write_enabled": bool(self.mcp_write_enabled),
            "simulate_bridge_failure": bool(self.simulate_bridge_failure),
            "last_screenshot_meta": dict(self.last_screenshot_meta) if self.last_screenshot_meta else None,
            "session_active": bool(self.session_active),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any] | None) -> "UIState":
        data = data or {}
        meta = data.get("last_screenshot_meta")
        return cls(
            advanced_open=bool(data.get("advanced_open", False)),
            debug_mode=bool(data.get("debug_mode", False)),
            explicit_override_mode=bool(data.get("explicit_override_mode", False)),
            mcp_write_enabled=bool(data.get("mcp_write_enabled", False)),
            simulate_bridge_failure=bool(data.get("simulate_bridge_failure", False)),
            last_screenshot_meta=dict(meta) if isinstance(meta, dict) else None,
            session_active=bool(data.get("session_active", False)),
        )


@dataclass
class OperationalState:
    """Operational bridge state kept while the legacy runtime still exists."""

    turn_counter: int = 0
    session_memory: dict[str, Any] = field(default_factory=dict)
    local_scope: dict[str, Any] = field(default_factory=dict)
    structural_index: dict[str, Any] = field(default_factory=dict)
    tree_structural_memory: dict[str, Any] = field(default_factory=dict)
    tree_change_markers: dict[str, Any] = field(default_factory=dict)
    recent_actions: list[dict[str, Any]] = field(default_factory=list)
    risky_events: list[dict[str, Any]] = field(default_factory=list)
    last_scene_summary: dict[str, Any] = field(default_factory=dict)
    last_gn_summary: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "turn_counter": int(self.turn_counter or 0),
            "session_memory": dict(self.session_memory) if isinstance(self.session_memory, dict) else {},
            "local_scope": dict(self.local_scope) if isinstance(self.local_scope, dict) else {},
            "structural_index": dict(self.structural_index) if isinstance(self.structural_index, dict) else {},
            "tree_structural_memory": (
                dict(self.tree_structural_memory) if isinstance(self.tree_structural_memory, dict) else {}
            ),
            "tree_change_markers": (
                dict(self.tree_change_markers) if isinstance(self.tree_change_markers, dict) else {}
            ),
            "recent_actions": [dict(item) for item in self.recent_actions if isinstance(item, dict)],
            "risky_events": [dict(item) for item in self.risky_events if isinstance(item, dict)],
            "last_scene_summary": dict(self.last_scene_summary) if isinstance(self.last_scene_summary, dict) else {},
            "last_gn_summary": dict(self.last_gn_summary) if isinstance(self.last_gn_summary, dict) else {},
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any] | None) -> "OperationalState":
        data = data or {}
        try:
            turn_counter = int(data.get("turn_counter") or 0)
        except Exception:
            turn_counter = 0
        return cls(
            turn_counter=turn_counter,
            session_memory=_as_dict(data.get("session_memory")),
            local_scope=_as_dict(data.get("local_scope")),
            structural_index=_as_dict(data.get("structural_index")),
            tree_structural_memory=_as_dict(data.get("tree_structural_memory")),
            tree_change_markers=_as_dict(data.get("tree_change_markers")),
            recent_actions=_as_list_of_dicts(data.get("recent_actions")),
            risky_events=_as_list_of_dicts(data.get("risky_events")),
            last_scene_summary=_as_dict(data.get("last_scene_summary")),
            last_gn_summary=_as_dict(data.get("last_gn_summary")),
        )


@dataclass
class Lifecycle:
    continuity_token: str = field(default_factory=new_continuity_token)
    prior_session_ids: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)

    def remember_prior_session(self, session_id: str) -> None:
        sid = str(session_id or "").strip()
        if not sid:
            return
        if sid in self.prior_session_ids:
            return
        self.prior_session_ids.append(sid)
        if len(self.prior_session_ids) > DEFAULT_MAX_PRIOR_SESSION_IDS:
            del self.prior_session_ids[:-DEFAULT_MAX_PRIOR_SESSION_IDS]

    def add_note(self, note: str) -> None:
        text = str(note or "").strip()
        if not text:
            return
        self.notes.append(text)
        if len(self.notes) > DEFAULT_MAX_LIFECYCLE_NOTES:
            del self.notes[:-DEFAULT_MAX_LIFECYCLE_NOTES]

    def to_dict(self) -> dict[str, Any]:
        return {
            "continuity_token": self.continuity_token,
            "prior_session_ids": list(self.prior_session_ids),
            "notes": list(self.notes),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any] | None) -> "Lifecycle":
        data = data or {}
        return cls(
            continuity_token=str(data.get("continuity_token") or new_continuity_token()),
            prior_session_ids=[str(item) for item in (data.get("prior_session_ids") or []) if str(item).strip()],
            notes=[str(item) for item in (data.get("notes") or []) if str(item).strip()],
        )


# ---------------------------------------------------------------------------
# Top-level Session
# ---------------------------------------------------------------------------


@dataclass
class Session:
    identity: Identity = field(default_factory=Identity)
    focus: Focus = field(default_factory=Focus)
    baseline_workspace: BaselineWorkspace = field(default_factory=BaselineWorkspace)
    history: History = field(default_factory=History)
    execution_state: ExecutionState = field(default_factory=ExecutionState)
    ui_state: UIState = field(default_factory=UIState)
    operational_state: OperationalState = field(default_factory=OperationalState)
    lifecycle: Lifecycle = field(default_factory=Lifecycle)

    # ---- invariants ------------------------------------------------------

    def update_focus(
        self,
        *,
        blend_path: str | None = None,
        object_name: str | None = None,
        modifier_name: str | None = None,
        tree_name: str | None = None,
    ) -> bool:
        """Update focus coordinates and enforce invariants.

        Returns ``True`` if the focus actually changed.
        """
        new_blend_path = self.focus.blend_path if blend_path is None else str(blend_path)
        new_object = self.focus.object_name if object_name is None else (str(object_name) if object_name else None)
        new_modifier = self.focus.modifier_name if modifier_name is None else (str(modifier_name) if modifier_name else None)
        new_tree = self.focus.tree_name if tree_name is None else (str(tree_name) if tree_name else None)
        new_signature = compute_focus_signature(new_blend_path, new_object, new_modifier, new_tree)
        if new_signature == self.focus.focus_signature:
            return False
        self.focus = Focus(
            blend_path=new_blend_path,
            object_name=new_object,
            modifier_name=new_modifier,
            tree_name=new_tree,
            focus_signature=new_signature,
            focus_changed_at=utc_now_iso(),
        )
        # The baseline was built against the old focus; mark it stale.
        self.baseline_workspace.mark_stale()
        return True

    def mark_baseline_stale(self) -> None:
        self.baseline_workspace.mark_stale()

    def touch(self) -> None:
        self.identity.touch()

    # ---- serialisation ---------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.identity.schema_version,
            "identity": self.identity.to_dict(),
            "focus": self.focus.to_dict(),
            "baseline_workspace": self.baseline_workspace.to_dict(),
            "history": self.history.to_dict(),
            "execution_state": self.execution_state.to_dict(),
            "ui_state": self.ui_state.to_dict(),
            "operational_state": self.operational_state.to_dict(),
            "lifecycle": self.lifecycle.to_dict(),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any] | None) -> "Session":
        data = data or {}
        identity = Identity.from_dict(data.get("identity"))
        # Always normalise the schema_version on the way in.
        identity.schema_version = SCHEMA_VERSION
        return cls(
            identity=identity,
            focus=Focus.from_dict(data.get("focus")),
            baseline_workspace=BaselineWorkspace.from_dict(data.get("baseline_workspace")),
            history=History.from_dict(data.get("history")),
            execution_state=ExecutionState.from_dict(data.get("execution_state")),
            ui_state=UIState.from_dict(data.get("ui_state")),
            operational_state=OperationalState.from_dict(data.get("operational_state")),
            lifecycle=Lifecycle.from_dict(data.get("lifecycle")),
        )

    @classmethod
    def new(cls, blend_path: str = "") -> "Session":
        """Construct an empty Session bound to ``blend_path``."""
        focus = Focus(blend_path=blend_path or "")
        return cls(focus=focus)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _optional_str(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value)
    return text if text else None


def _as_dict(value: Any) -> dict[str, Any]:
    return dict(value) if isinstance(value, dict) else {}


def _as_list_of_dicts(value: Any) -> list[dict[str, Any]]:
    if not isinstance(value, list):
        return []
    out: list[dict[str, Any]] = []
    for item in value:
        if isinstance(item, dict):
            out.append(dict(item))
    return out
